### PR TITLE
Initial implementation of async/await support

### PR DESCRIPTION
**Pull request by sharwell**
This pull request adds support for async/await in .NET 3.5 applications. The implementation is based on code in https://github.com/Microsoft/referencesource, which has been modified as follows:

* Updated to build without warnings with our StyleCop Analyzers configuration
* Minor updates to support .NET 3.5 and .NET 4.5 in a consistent manner

### CODE REVIEW

**Comment by terrajobst** [comment]
I’m checking whether we can make `Microsoft.Bcl` and `Microsoft.Bcl.Async` available as MIT licensed .NET Reference Source. No promises, but I’ll try.

**Comment by sharwell** [comment]
@terrajobst This pull request now includes a fair number of tests for the new functionality, proving that it does bring async/await support to .NET 3.5. :tada:

**Comment by sharwell** [comment]
@terrajobst Any update on this? :smile:

**Comment by sharwell** [comment]
I had to move this back to 2.1.0 since it's not yet approved and I need to release a stable version 2.0.0.

**Comment by terrajobst** [comment]
@sharwell Sorry for the long delay. I think I got some traction on this now. Will keep you posted.

**Comment by sharwell** [comment]
:open_mouth: :smile:

**Comment by terrajobst** [comment]
OK, I've clarified the licenses and submitted PR to the Microsoft Reference Source repository: https://github.com/Microsoft/referencesource/pull/17 which officially identifies the source as MIT licensed.

I assume this is enough to unblock your work?

**Comment by terrajobst** [comment]
The PR is now merged :smile:

drops-mic

**Comment by sharwell** [comment]
:tada: I'll make sure I get the notices for this project updated but I'm pretty sure this is :tada: !!

**Pull request merged**
